# Generated by Django 5.0.6 on 2024-06-28 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='has_capacity',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 28, 14, 19, 5, 916147, tzinfo=datetime.timezone.utc)),
        ),
    ]
