# Generated by Django 5.0.6 on 2024-06-28 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='remaining_capacity',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 28, 12, 44, 52, 242404, tzinfo=datetime.timezone.utc)),
        ),
    ]
